version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 637714898786.dkr.ecr.us-east-1.amazonaws.com
      - REPO_URI=637714898786.dkr.ecr.us-east-1.amazonaws.com/ecs-flask-repo
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPO_URI:latest .
      - docker tag $REPO_URI:latest $REPO_URI:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPO_URI:latest
      - printf '[{"name":"ecs-flask-container","imageUri":"%s"}]' $REPO_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
